Nesses jupyter notebooks, irei apresentar os códigos que estão exposto no corpo do texto do artigo.

Caso você as bibliotecas não estejam instaladas, execute o comando abaixo:
pip install --upgrade numpy scikit-learn

In [14]:
# Execute esse comando só a primeira vez que for rodar o código
# Caso você as bibliotecas não estejam instaladas, execute o comando abaixo:
!pip install scikit-learn numpy

Agora vamos verificar as versoes do python numpy e sklearn , para voce reproduzir os resultados


In [15]:
import sys
import numpy
import sklearn

# Exibe a versão do Python em uso
print("Python:", sys.version)
# Exibe a versão do NumPy instalada
print("NumPy:", numpy.__version__)
# Exibe a versão do scikit-learn instalada
print("scikit-learn:", sklearn.__version__)

# Comentário:
# É importante imprimir as versões das bibliotecas e do Python para garantir a reprodutibilidade dos experimentos.
# Diferentes versões podem apresentar diferenças de comportamento, funções ou resultados.

Python: 3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]
NumPy: 2.0.2
scikit-learn: 1.6.1


### Entradas (inputs)

In [16]:
# Importando as biblioteca
from sklearn import datasets
dataset = datasets.load_iris()

j = 0 # Indice dos dados
x_j = dataset.data[j,:] # Entrada
y_j = dataset.target[j] # Alvo
print(x_j, y_j)

[5.1 3.5 1.4 0.2] 0


###  Pesos e bias:

In [17]:
import numpy as np

w = [1, 0, 0.5, -0.3]
b = [0.5]
z = np.dot(w,x_j) + b
print(z)

[6.24]


### Função de ativação:

In [18]:
# considerando o valor de z, obtido anteriomente
# z = [6.24]
def ativacao_sigmoide(z):
  f = 1/(1+np.exp(-z))
  return f

y_hat = ativacao_sigmoide(z)
print(y_hat)

[0.99805394]


### Função de custo

In [19]:
# y_hat = [0.998], y_0 = [0]
#calculo do erro quadratico com j=0
loss = (y_j- y_hat)**2
print(loss)

[0.99611167]


### Regra de aprendizado dos parâmetro

In [20]:
eta = 0.01

w = w - 2*eta*( y_j - y_hat)*y_hat*(1-y_hat)*x_j
b = b - 2*eta*( y_j - y_hat)*y_hat*(1-y_hat)
print(w,b)

[ 1.00019773e+00  1.35694583e-04  5.00054278e-01 -2.99992246e-01] [0.50003877]


### Juntando

In [21]:
w = [1, 0, 0.5, -0.3]
b = [0.5]
M = 150
eta = 0.01
Loss = 0
for j in range(M):
  x_j = dataset.data[j,:] # Entrada
  y_j = dataset.target[j] # Alvo/rotulo
  z = np.dot(w,x_j) + b
  y_hat = ativacao_sigmoide(z)
  w = w - 2*eta*(y_j-y_hat)*y_hat*(1-y_hat)*x_j
  b = b - 2*eta*(y_j-y_hat)*y_hat*(1-y_hat)
  loss += (y_j-y_hat)**2/M

Essa é a loss para primeira época

In [22]:
loss

array([1.66141792])